/*
	EXERCICIO 3 -
		SIMULAR MULTIPLAS PILHAS UTILIZANDO UMA MATRIZ DE INTEIROS. CADA COLUNA DA MATRIZ
		REPRESENTA UMA PILHA. A VARIAVEL TOPO PARA CADA PILHA SERA COLOCADA NA ULTIMA LINHA DA MATRIZ
		ESCREVA AS FUNCOES PRIMITIVAS PARA MANIPULACAO DE PILHA USANDO A ESTRUTURA APRESENTADADA
*/
