/*
	1) ESCREVER UMA FUNCAO EM C PARA VERIFICAR SE UMA MATRIZ QUADRADA 5X5 DE INTEIROS FORMA UM QUADRADO MAGICO.
		A FUNCAO RETORNA 1 SE FOR QUADRADO MAGICO. SE NAO FOR RETORNA 0;
		QUADRADO MAIGCO = A SOMA DE CADA UMAS DAS LINHAS É IGUAL A SOMA DE CADA UMA DAS COLUNAS, 
		QUE É IGUAL A SOMA DOS ELEMENTOS DA SOMA DA DIAGONAL PRINCIPAL E DA DIAGONAL SECUNDARIA
	
	2) REPRESENTAR UM NUMERO INTEIRO COMO UM VETOR DE INTEIROS (CADA ELEMENTO DO VETOR É UM NUMERO DE 1 DIGITO).
		ESCREVA UM FUNCAO PARA SOMAR DOIS INTEIROS UTILIZANDO ESSA REPRESENTACAO;
		
	3) ESCREVA UM PROGRAMA EM C QUE CONTENHA UMA FUNCAO PARA VERIFICAR SE UMA MATRIZ É UMA
		MATRIZ IDENTIDADE. UMA MATRIZ IDENTIDADE É AQUELA QUE É FORMADA POR ZEROS E UNS.
		ONDE CADA LINHA POSSUI APENAS UM ELEMENTO IGUAL A 1 E CADA COLUNA POSSUI UM UNICO ELEMENTO IGUAL A 	
		
	4) UM ESTACIONAMENTO CONTEM UMA UNICA ALAMEDA QUE GUARDA 100 CARROS. EXISTEM APENAS UMA ENTRADA/SAIDA
	NO ESTACIONAMENTO, EM UMA EXTREMIDADE DA ALAMEDA. SE CHEGAR UM CLIENTE PARA RETIRAR UM CARRO QUE NAO SEJA
	O MAIS PROXIMO DA SAIDA, TODOS OS CARROS BLOQUEANDO SEU CAMINHO SAIRAO DO ESTACIONAMENTO, O CARRO DO
	CLIENTE SERA MANDADO PARA FORA DO ESTACIONAMENTO E OS OUTROS CARROS VOLTARAO A OCUPAR A MESMA SEQUENCIA 
	INICIAL. ESCREVA UM PROGRAMA EM C PARA REALIZAR A ENTRADA E SAIDA DE CARROS
		O CARRO É IDENTIFICADO PELA SUA PLACA. QUANDO UM CARRO CHEGAR DEVE ESPECIFICAR	
*/
